### ISSUE TITLE
Same config, but seems not to converge.

### ISSUE THREAD

**Issue by whwczxm** [kongzelun/cpl#1]
Thanks for you high-quality work.
However when trying to train the network on my own platform with the same config and the same net, the loss didn't go down and finish at an unacceptable ~20% accuracy. I've tried all 3 losses (CEL, GCPL, PDCE) and almost every config.json in your project. 
According to your log file, it should be easy to converge and get to 80%+ accuracy easily. 
1. So could you please test your code again with presented config.json on CIFAR10 or Fashion-Mnist?  
2. And I wonder why the batchsize is set to 1, because the original implementation's batchsize is 50 by default. And I've tried to modify the batchsize to 16, it didn't converge either.

您好，非常感谢您的高质量工作。但是我在使用的过程中无论使用任何loss（CEL, GCPL, PDCE）或各种Config的设置都不能达到您在日志文件中所记录的精度（测试了CIFAR10和Fashion-mnist）实际上网络完全不收敛，loss在1~2左右浮动，acc只有20%不到）。我想知道您是否是为了其他数据集修改了代码结构，导致在使用目前已有的config.json中的设置时网络不收敛。
恳请您再次测试代码，您看您现在是否依然可以使用根目录下finish文件夹中的config达到80%以上的精度。
另外一点是在输入时batch被设置为1，而在原作者实现中采用的是50或更高，一般来说网络的batch也不会设置为1，不知道您这样做是为了什么？（我们也尝试将您的代码修改为更高的batchsize，但是依然不收敛。）
使用中文可能有些唐突，非常感谢您。

**Comment by Vitvicky** [comment]
Thank you for your interesting and question, sorry that we response a little late. You could see the updated version on: https://github.com/kongzelun/cpe. Maybe this version is not the nearest one. Also, for the batch, we have changed the value in the CPE code, you could select 50% categories from the total class set as the initial one, and rest as the novel class. Thanks

**Comment by Vitvicky** [comment]
> Thanks for you high-quality work.
> However when trying to train the network on my own platform with the same config and the same net, the loss didn't go down and finish at an unacceptable ~20% accuracy. I've tried all 3 losses (CEL, GCPL, PDCE) and almost every config.json in your project.
> According to your log file, it should be easy to converge and get to 80%+ accuracy easily.
> 
> 1. So could you please test your code again with presented config.json on CIFAR10 or Fashion-Mnist?
> 2. And I wonder why the batchsize is set to 1, because the original implementation's batchsize is 50 by default. And I've tried to modify the batchsize to 16, it didn't converge either.
> 
> 您好，非常感谢您的高质量工作。但是我在使用的过程中无论使用任何loss（CEL, GCPL, PDCE）或各种Config的设置都不能达到您在日志文件中所记录的精度（测试了CIFAR10和Fashion-mnist）实际上网络完全不收敛，loss在1~2左右浮动，acc只有20%不到）。我想知道您是否是为了其他数据集修改了代码结构，导致在使用目前已有的config.json中的设置时网络不收敛。
> 恳请您再次测试代码，您看您现在是否依然可以使用根目录下finish文件夹中的config达到80%以上的精度。
> 另外一点是在输入时batch被设置为1，而在原作者实现中采用的是50或更高，一般来说网络的batch也不会设置为1，不知道您这样做是为了什么？（我们也尝试将您的代码修改为更高的batchsize，但是依然不收敛。）
> 使用中文可能有些唐突，非常感谢您。
Thank you for your interesting and question, sorry that we response a little late. You could see the updated version on: https://github.com/kongzelun/cpe. Maybe this version is not the nearest one. Also, for the batch, we have changed the value in the CPE code, you could select 50% categories from the total class set as the initial one, and rest as the novel class. Thanks
